name: Trent_SkyBlock
authors:
  - Trent
version: '1.5'

main: me.trent.skyblock.SkyBlock

depend:
  - WorldEdit
  - Vault
  - Essentials

softdepend:
  - WildStacker
  - Votifier
  - PlaceholderAPI
  - MVdWPlaceholderAPI

load: POSTWORLD